name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["14.x", "16.x"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Run Nigiri
        uses: vulpemventures/nigiri-github-action@v1

      - name: Install dependencies
        run: npm install --ci

      - name: Lint
        run: |
          npm run format:ci
          npm run lint
          npm run lint:tests

      - name: Coverage
        run: npm run coverage

      - name: Unit Test
        run: npm run unit

      - name: Integration Test
        env:
          APIURL: http://localhost:3001
        run: npm run integration
